const emptyClient = {
  name: "",
  contact_name: "",
  email: "",
  contact_email: "",
  phone: "",
  contact_phone: "",
  company: "",
  website: "",
  invoice_email: "",
  address: "",
};

const emptyInvoice = {
  client_id: "",
  quote_id: "",
  display_id: "",
  is_legacy: false,
  title: "",
  status: "draft",
  due_date: null,
  notes: "",
  line_items: [
    {
      description: "",
      quantity: 1,
      unit_amount: "",
      tax_code: "standard",
      tax_rate: 0,
      tax_kind: "vat",
      tax_inclusive: false,
      tax_override: false,
    },
  ],
  issued_at: null,
  recurrence_enabled: false,
  recurrence_frequency: "monthly",
  recurrence_count: 1,
  recurrence_day_of_month: "",
  due_rule_unit: "days",
  due_rule_value: 30,
  send_now: false,
};

const emptyQuote = {
  client_id: "",
  display_id: "",
  is_legacy: false,
  title: "",
  status: "draft",
  valid_until: null,
  notes: "",
  line_items: [
    {
      description: "",
      quantity: 1,
      unit_amount: "",
      tax_code: "standard",
      tax_rate: 0,
      tax_kind: "vat",
      tax_inclusive: false,
      tax_override: false,
    },
  ],
};

const emptyAgreement = {
  client_id: "",
  display_id: "",
  quote_id: "",
  title: "",
  start_date: null,
  end_date: null,
  current_version: 1,
  updated_at: null,
  updated_by_email: "",
  scope_of_services: "",
  duration: "",
  availability: "",
  meetings: "",
  access_requirements: "",
  fees_payments: "",
  data_protection: "",
  termination: "",
  company_signatory_name: "",
  company_signatory_title: "",
  company_signed_date: null,
  client_signatory_name: "",
  sla_items: [{ sla: "", timescale: "" }],
};

const emptyProposal = {
  client_id: "",
  display_id: "",
  quote_id: "",
  title: "",
  status: "draft",
  submitted_on: null,
  valid_until: null,
  current_version: 1,
  updated_at: null,
  updated_by_email: "",
  summary: "",
  approach: "",
  timeline: "",
  content: "",
  requirements: [{ description: "" }],
  attachments: [],
};

const emptyExpense = {
  client_id: "",
  user_id: "",
  display_id: "",
  is_legacy: false,
  title: "",
  amount: "",
  tax_code: "standard",
  tax_rate: 0,
  tax_kind: "vat",
  tax_inclusive: false,
  vat_reclaimable: false,
  incurred_date: null,
  notes: "",
  receipts: [],
};

const emptyCreditNote = {
  invoice_id: "",
  issued_at: null,
  notes: "",
  line_items: [],
};

const emptyRefund = {
  credit_note_id: "",
  refunded_at: null,
  amount: "",
  notes: "",
};

const emptyEmailDraft = {
  entity_type: "invoice",
  entity_id: "",
  client_id: "",
  selected_items: [],
  to_email: "",
  to_email_overrides: {},
  subject_overrides: {},
  body_overrides: {},
  include_proposal_assets: true,
  send: false,
};

const defaultSettings = {
  company_name: "Your Company",
  company_address: "",
  company_invoice_email: "",
  invoice_prefix: "INV",
  quote_prefix: "QUOTE",
  proposal_prefix: "PROP",
  agreement_prefix: "AGR",
  expense_prefix: "EXP",
  credit_note_prefix: "CN",
  refund_prefix: "RF",
  fy_start_month: 1,
  fy_start_day: 1,
  fy_end_month: 12,
  fy_end_day: 31,
  accounts_due_month: 10,
  accounts_due_day: 31,
  confirmation_date_month: 1,
  confirmation_date_day: 27,
  confirmation_due_month: 2,
  confirmation_due_day: 10,
  smtp_host: "",
  smtp_port: 587,
  smtp_username: "",
  smtp_password: "",
  smtp_from: "",
  smtp_use_tls: true,
  bank_name: "",
  bank_account_name: "",
  bank_account_number: "",
  bank_sort_code: "",
  bank_iban: "",
  bank_swift: "",
  bank_reference: "",
  vat_registered: false,
  vat_registration_date: null,
  vat_number: "",
  utr: "",
  company_number: "",
  business_tax_mode: "limited_company",
  vat_scheme: "standard",
  default_vat_rate: 20,
  default_vat_code: "standard",
  vat_inclusive_default: false,
  vat_filing_frequency: "quarterly",
  vat_period_start_month: 1,
  vat_period_start_day: 1,
  vat_next_filing_due: null,
  vat_accounting_method: "accrual",
  corporation_tax_enabled: false,
  corporation_tax_reference: "",
  corporation_tax_rate: 25,
  corporation_tax_period_start_month: 1,
  corporation_tax_period_start_day: 1,
  corporation_tax_payment_due: null,
  corporation_tax_return_due: null,
  tax_estimate_basis: "accrual",
  tax_policy_effective_date: null,
  tax_policy_last_reviewed: null,
  tax_policy_next_review_due: null,
  tax_policy_review_notes: "",
  other_taxes: [],
  filing_checklist_state: {},
};

export {
  emptyClient,
  emptyInvoice,
  emptyQuote,
  emptyAgreement,
  emptyProposal,
  emptyExpense,
  emptyCreditNote,
  emptyRefund,
  emptyEmailDraft,
  defaultSettings,
};
