"""add_invoice_quote_link

Revision ID: 11f0bd851dde
Revises: c09c6a2324da
Create Date: 2026-02-06 12:22:24.281619
"""
from alembic import op
import sqlalchemy as sa


revision = '11f0bd851dde'
down_revision = 'c09c6a2324da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('quote_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_invoices_quote_id_quotes',
            'quotes',
            ['quote_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_constraint('fk_invoices_quote_id_quotes', type_='foreignkey')
        batch_op.drop_column('quote_id')
    # ### end Alembic commands ###
