"""add_expense_receipts

Revision ID: 5dbd257f9f91
Revises: 11f0bd851dde
Create Date: 2026-02-06 15:53:13.099106
"""
from alembic import op
import sqlalchemy as sa


revision = '5dbd257f9f91'
down_revision = '11f0bd851dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_receipts_id'), 'expense_receipts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_receipts_id'), table_name='expense_receipts')
    op.drop_table('expense_receipts')
    # ### end Alembic commands ###
