"""initial

Revision ID: c09c6a2324da
Revises: 
Create Date: 2026-02-04 12:48:06.927311
"""
from alembic import op
import sqlalchemy as sa


revision = 'c09c6a2324da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('invoice_email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.String(length=300), nullable=True),
    sa.Column('company_invoice_email', sa.String(length=200), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('quote_prefix', sa.String(length=20), nullable=False),
    sa.Column('proposal_prefix', sa.String(length=20), nullable=False),
    sa.Column('agreement_prefix', sa.String(length=20), nullable=False),
    sa.Column('expense_prefix', sa.String(length=20), nullable=False),
    sa.Column('fy_start_month', sa.Integer(), nullable=False),
    sa.Column('fy_start_day', sa.Integer(), nullable=False),
    sa.Column('fy_end_month', sa.Integer(), nullable=False),
    sa.Column('fy_end_day', sa.Integer(), nullable=False),
    sa.Column('accounts_due_month', sa.Integer(), nullable=False),
    sa.Column('accounts_due_day', sa.Integer(), nullable=False),
    sa.Column('confirmation_date_month', sa.Integer(), nullable=False),
    sa.Column('confirmation_date_day', sa.Integer(), nullable=False),
    sa.Column('confirmation_due_month', sa.Integer(), nullable=False),
    sa.Column('confirmation_due_day', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=200), nullable=True),
    sa.Column('smtp_password', sa.String(length=200), nullable=True),
    sa.Column('smtp_from', sa.String(length=200), nullable=True),
    sa.Column('smtp_use_tls', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_sort_code', sa.String(length=50), nullable=True),
    sa.Column('bank_iban', sa.String(length=100), nullable=True),
    sa.Column('bank_swift', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_sort_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=30), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('incurred_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_display_id'), 'expenses', ['display_id'], unique=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=30), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_display_id'), 'invoices', ['display_id'], unique=True)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=30), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_display_id'), 'quotes', ['display_id'], unique=True)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_id'), 'invoice_line_items', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=30), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_display_id'), 'proposals', ['display_id'], unique=True)
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_id'), 'quote_line_items', ['id'], unique=False)
    op.create_table('service_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=30), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('scope_of_services', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('meetings', sa.Text(), nullable=True),
    sa.Column('access_requirements', sa.Text(), nullable=True),
    sa.Column('fees_payments', sa.Text(), nullable=True),
    sa.Column('data_protection', sa.Text(), nullable=True),
    sa.Column('termination', sa.Text(), nullable=True),
    sa.Column('company_signatory_name', sa.String(length=200), nullable=True),
    sa.Column('company_signatory_title', sa.String(length=200), nullable=True),
    sa.Column('company_signed_date', sa.DateTime(), nullable=True),
    sa.Column('client_signatory_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_agreements_display_id'), 'service_agreements', ['display_id'], unique=True)
    op.create_index(op.f('ix_service_agreements_id'), 'service_agreements', ['id'], unique=False)
    op.create_table('agreement_slas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('sla', sa.String(length=300), nullable=False),
    sa.Column('timescale', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['service_agreements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_slas_id'), 'agreement_slas', ['id'], unique=False)
    op.create_table('proposal_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_attachments_id'), 'proposal_attachments', ['id'], unique=False)
    op.create_table('proposal_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_requirements_id'), 'proposal_requirements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_requirements_id'), table_name='proposal_requirements')
    op.drop_table('proposal_requirements')
    op.drop_index(op.f('ix_proposal_attachments_id'), table_name='proposal_attachments')
    op.drop_table('proposal_attachments')
    op.drop_index(op.f('ix_agreement_slas_id'), table_name='agreement_slas')
    op.drop_table('agreement_slas')
    op.drop_index(op.f('ix_service_agreements_id'), table_name='service_agreements')
    op.drop_index(op.f('ix_service_agreements_display_id'), table_name='service_agreements')
    op.drop_table('service_agreements')
    op.drop_index(op.f('ix_quote_line_items_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_display_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_invoice_line_items_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_display_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_display_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_display_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
