"""add comment metadata

Revision ID: c0c27e07ad81
Revises: 6d6127209dab
Create Date: 2026-02-12 10:55:07.961660
"""
from alembic import op
import sqlalchemy as sa


revision = 'c0c27e07ad81'
down_revision = '6d6127209dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreement_version_comments') as batch_op:
        batch_op.add_column(sa.Column('mentions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('implemented', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    with op.batch_alter_table('proposal_version_comments') as batch_op:
        batch_op.add_column(sa.Column('mentions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('implemented', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_version_comments') as batch_op:
        batch_op.drop_column('implemented')
        batch_op.drop_column('mentions')
    with op.batch_alter_table('agreement_version_comments') as batch_op:
        batch_op.drop_column('implemented')
        batch_op.drop_column('mentions')
    # ### end Alembic commands ###
