#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs/wiki"
NAV_FILE="$DOCS_DIR/nav.json"
OUT_FILE="$DOCS_DIR/INDEX.md"

if [[ ! -f "$NAV_FILE" ]]; then
  echo "nav.json not found at $NAV_FILE"
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "node is required to build index"
  exit 1
fi

node - <<'NODE' "$NAV_FILE" "$OUT_FILE"
const fs = require('fs');
const navPath = process.argv[2];
const outPath = process.argv[3];
const nav = JSON.parse(fs.readFileSync(navPath, 'utf8'));

const groups = new Map();
for (const page of nav.pages) {
  if (!groups.has(page.group)) groups.set(page.group, []);
  groups.get(page.group).push(page);
}

let out = '# Wiki Index\n\n';
out += 'Auto-generated from `docs/wiki/nav.json`.\n\n';
out += '> Do not edit this file directly. Run `scripts/wiki-build-index.sh`.\n\n';

for (const [group, pages] of groups.entries()) {
  out += `## ${group}\n\n`;
  for (const page of pages) {
    const stem = page.file.replace(/\.md$/i, '');
    out += `- [${page.title}](./${stem})\n`;
  }
  out += '\n';
}

fs.writeFileSync(outPath, out);
NODE

echo "Generated $OUT_FILE"
